site_name: VSUP

# theme:
#   name: "material"
theme: readthedocs

repo_name: VSUP
repo_url: https://github.com/JohnGoertz/vsup
site_url: https://JohnGoertz.github.io/vsup

plugins:
- search
- marimo
- mkdocs-autoapi:
    autoapi_dir: vsup
- mkdocstrings

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

nav:
  - Overview: index.md
